name: Monitorar e Enviar Email

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  monitorar-e-notificar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt

      - name: Executar script Python
        id: exec
        run: python script.py

      - name: Verificar se houve mudanças em resultados.json
        id: diff
        run: |
          git add resultados.json verificados.json
          git diff --cached --exit-code || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & push (se houver mudanças)
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Atualização automática: resultados"
          git push

      - name: Enviar e-mail se houver resultados novos
        if: steps.diff.outputs.changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Monitoramento de Nome – novos resultados encontrados"
          to: ${{ secrets.EMAIL_USER }}
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Olá!

            Foram encontrados novos resultados no monitoramento de nome.

            Consulte o arquivo `resultados.json` no seu repositório para ver os detalhes.

          secure: true
