name: Monitoramento de Nome

on:
  schedule:
    - cron: '0 6 */2 * *' # Executa a cada 2 dias às 06:00 UTC (03:00 BRT)
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de monitoramento
        run: python monitor.py

      - name: Enviar e-mail com resultados encontrados
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Monitoramento de Nome – novos resultados encontrados
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Olá!

            Foram encontrados novos resultados no monitoramento de nome.

            Consulte o arquivo `resultados.json` no seu repositório para ver os detalhes.
