name: Monitoramento de Nome

on:
  schedule:
    - cron: '0 6 */2 * *' # Executa a cada 2 dias às 06:00 UTC (03:00 BRT)
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de monitoramento
        run: python script.py

      - name: Commit e push de arquivos atualizados
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add resultados.json verificados.json || true
          git diff --cached --quiet || git commit -m "Atualizar resultados e verificados.json [bot]"
          git push origin HEAD:${{ github.ref }}

      - name: Enviar e-mail com resultados encontrados
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Monitoramento de Nome – novos resultados encontrados
          to: ${{ secrets.EMAIL_USER }}
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Olá!

            Foram encontrados novos resultados no monitoramento de nome.

            Consulte o arquivo `resultados.json` no seu repositório para ver os detalhes.
